# Linear Algebra

#### Importing Packages
Python has an extensive collection of third-party libraries, or ***packages***, with additional functions, data-structures, etc.  Many (most?) packages of interest are hosted on the Python Package Index ***pypi***, and can be installed into your environment using ***pip***.  The Anaconda distribution in the pre-work includes a number of these that are useful in data science, so you should have most of them installed already.  

ref:  https://pypi.python.org/pypi

A note on namespaces when importing - there are a few different ways to import:

    1. import numpy

    - all submodules of numpy are accessible in the numpy namespace
    - e.g. numpy.array([1,2,3])


    2. import numpy as np

    - same as 1 except an alias 'np' is created for the namespace instead
    - e.g. np.array([1,2,3])


    3. from numpy import *

    - adds all submodules to global namespace
    - e.g. array([1,2,3])
    - Note: This can be dangerous because if different modules have submodules with the same name than whatever is imported last will overrite what came before it - i.e. naming collision -> overwriting!.
    
    4. from numpy import array
    
    - will import only the indicated submodules into the global namespace
    - e.g. array([1,2,3])
    - Note: can be ok since you are being explicit
    
    We will generally use 2 and 4 (sparingly)

### NumPy

As we've seen in lecture, linear algebra is the branch of mathematics describing navigation between different vector spaces. This core concept is very important as various data science techniques rely upon it (e.g. Linear Regression, Support Vector Machines, Recommender Systems, Neural Networks).

NumPy is a package designed to be used in scientific computing, and specifically around building and manipulating N-dimensional array objects.

In [34]:
import numpy

import numpy as np

from numpy import absolute

# The next one is dangerous to do, and not recommended 
# except in cases where you know why you're using it
# from numpy import *

Now we can do the same thing three ways

In [35]:
print numpy.absolute(-10)
print np.absolute(-10)
print absolute(-10)

10
10
10


We can create the Linear Algebra Objects we saw in lecture

In [36]:
vector = np.array([1, 2, 1])
vector
# np.shape(data)

array([1, 2, 1])

In [37]:
data = np.array([[1, 2, 3],[2, 4, 9]])
data

array([[1, 2, 3],
       [2, 4, 9]])

In [38]:
data[0]  # first row

array([1, 2, 3])

In [39]:
data[ : , 1]  # all rows, second column

array([2, 4])

In [40]:
vector1 = np.array([[1,2,3]])
vector1

array([[1, 2, 3]])

In [41]:
np.dot(data,vector1)

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

Numpy lets us perform matrix operations

In [42]:
np.dot(data, vector)

array([ 8, 19])

We can transpose an array

In [43]:
print data
print data.T

[[1 2 3]
 [2 4 9]]
[[1 2]
 [2 4]
 [3 9]]


#### Creating a square matrix array

In [44]:
a = np.arange(25).reshape(5,5)
# arange(n) is a function that creates a 1 row array of integers of length n 
# reshape(M,N) is a method converts a list to a matrix of size MxN
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
biga = a*10
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [28]:
print biga.mean()
print biga.mean(axis=0) #Average per column 
biga.mean(1) #average per row
# type(biga.mean(1))

120.0
[ 100.  110.  120.  130.  140.]


array([  20.,   70.,  120.,  170.,  220.])

Creating a matrix with numpy

In [29]:
biga-20

array([[-20, -10,   0,  10,  20],
       [ 30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170],
       [180, 190, 200, 210, 220]])

In [30]:
bigm = np.matrix(biga-20)
bigm

matrix([[-20, -10,   0,  10,  20],
        [ 30,  40,  50,  60,  70],
        [ 80,  90, 100, 110, 120],
        [130, 140, 150, 160, 170],
        [180, 190, 200, 210, 220]])

Creating the Inverse of a Matrix

In [32]:
np.linalg.inv(bigm)

matrix([[ -2.81474977e+13,  -1.52777778e-03,   5.62949953e+13,
          -2.22222222e-02,  -2.81474977e+13],
        [  3.51843721e+13,   2.25000000e-02,  -5.27765581e+13,
          -3.51843721e+13,   5.27765581e+13],
        [ -4.22212465e+13,   9.38249922e+13,  -7.97512434e+13,
           4.69124961e+13,  -1.87649984e+13],
        [  9.14793674e+13,  -1.87649984e+14,   9.26521798e+13,
           1.17281240e+13,  -8.20968682e+12],
        [ -5.62949953e+13,   9.38249922e+13,  -1.64193736e+13,
          -2.34562481e+13,   2.34562481e+12]])

#### Slices

In [33]:
type(bigm)

numpy.matrixlib.defmatrix.matrix

In [34]:
bigm = np.array(bigm)
print bigm
bigm[0]

[[-20 -10   0  10  20]
 [ 30  40  50  60  70]
 [ 80  90 100 110 120]
 [130 140 150 160 170]
 [180 190 200 210 220]]


array([-20, -10,   0,  10,  20])

In [37]:
#Same thing, but demonstrating the full slice with a colon
print biga
biga[0,:]
biga[:,2] #pull out middle column

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]]


array([ 20,  70, 120, 170, 220])

#### Describing your Arrays

In [45]:
compa = np.arange(30).reshape(5,3,2)
compa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [46]:
# lets describe it
print compa.shape
print compa.ndim
print compa.dtype

(5, 3, 2)
3
int64


In [40]:
compa[3,:,1] #4th matrix 2nd column

array([19, 21, 23])

In [44]:
# We can assign values using list-like index
# But be careful on types
compa[0,0,0] = float(5.9)
compa[0,0,0]

5

In [45]:
compa

array([[[ 5,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

We can change the datatype when needed

In [47]:
compa = compa.astype(float) #so you can have decimals
compa[0,0,0] = 5.75
compa[0,0,0]

5.75

In [48]:
compa

array([[[  5.75,   1.  ],
        [  2.  ,   3.  ],
        [  4.  ,   5.  ]],

       [[  6.  ,   7.  ],
        [  8.  ,   9.  ],
        [ 10.  ,  11.  ]],

       [[ 12.  ,  13.  ],
        [ 14.  ,  15.  ],
        [ 16.  ,  17.  ]],

       [[ 18.  ,  19.  ],
        [ 20.  ,  21.  ],
        [ 22.  ,  23.  ]],

       [[ 24.  ,  25.  ],
        [ 26.  ,  27.  ],
        [ 28.  ,  29.  ]]])

#### Stacking arrays

You must stack using dimensions of the same size

In [47]:
a = np.array((1,2,3))
b = np.array((2,3,4))
print 'H Stack'
print np.hstack((a,b))
print 'V Stack'
print np.vstack((a,b))
print a.shape

H Stack
[1 2 3 2 3 4]
V Stack
[[1 2 3]
 [2 3 4]]
(3,)


In [54]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print 'H Stack'
print np.hstack((a,b))
print 'V Stack'
print np.vstack((a,b))
print a.shape

H Stack
[[1 2]
 [2 3]
 [3 4]]
V Stack
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
(3, 1)


### Using Random Numbers

Random numbers are very helpful and are necessary at times for testing data pipelines and running statistical analyses. Functions for creating random values are under numpy.random.

In [63]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.30357058,  0.93826429,  0.82353635,  0.8038382 ,  0.48510866],
       [ 0.268827  ,  0.09622206,  0.44500937,  0.46003466,  0.07425354],
       [ 0.87899065,  0.44571146,  0.80684532,  0.33507226,  0.26768035],
       [ 0.90304757,  0.60097637,  0.34066423,  0.0794192 ,  0.87757891],
       [ 0.60341963,  0.72830252,  0.56508823,  0.66555468,  0.98108631]])

In [62]:
rm.shape

(5, 5)

You can shuffle values randomly as well

In [64]:
# This will shuffle along the first index of a multi-dimensional array
np.random.shuffle(rm)
rm

array([[ 0.90304757,  0.60097637,  0.34066423,  0.0794192 ,  0.87757891],
       [ 0.87899065,  0.44571146,  0.80684532,  0.33507226,  0.26768035],
       [ 0.60341963,  0.72830252,  0.56508823,  0.66555468,  0.98108631],
       [ 0.268827  ,  0.09622206,  0.44500937,  0.46003466,  0.07425354],
       [ 0.30357058,  0.93826429,  0.82353635,  0.8038382 ,  0.48510866]])

In [66]:
print rm.mean()
print rm.mean(0) #Average per column
print rm.mean(1) #average per row only this changes after s

0.551124095554
[ 0.59157109  0.56189534  0.5962287   0.4687838   0.53714155]
[ 0.56033725  0.54686001  0.70869027  0.26886933  0.67086361]


In [67]:
# for a different Normal Distribution, use np.random.normal
rm = np.random.normal(5,9,(30,30))
rm

array([[  1.29482814e+00,   5.02651203e+00,   2.65632351e+01,
         -9.50412190e+00,   2.19585860e+00,   2.88986494e+00,
          2.00959014e+01,   9.24500248e+00,   1.64477641e+00,
          7.54160273e-01,   2.99839926e+00,   8.08652183e+00,
          6.35179614e+00,  -1.64271165e+00,   5.27267425e+00,
          2.61734914e-02,  -2.96952868e+00,   6.66794372e+00,
          5.16878242e+00,   1.27612504e+01,   8.23617538e+00,
          2.73888136e+00,   5.25166463e+00,   1.95275829e+01,
          1.73014642e+01,  -3.52150512e+00,  -9.62189574e+00,
          5.83704808e+00,   4.83578124e+00,   2.91439899e+00],
       [  7.24269360e+00,   9.57374606e+00,   7.15201330e+00,
          8.76319358e+00,   6.49035331e+00,  -4.69713197e+00,
         -5.16899101e+00,  -1.48519099e+01,   3.66299142e+00,
         -6.19753669e+00,   6.12095852e+00,  -1.68682098e-01,
          2.20369026e+01,  -9.62008677e+00,   1.11991234e+01,
         -1.14395460e+01,  -1.24050098e+01,   8.15608447e+00,
       

In [68]:
print rm.mean(), "which is hopefully close to the input mean"
print rm.var(), "which variance = stdev squared"
print np.median(rm)

4.82926388474 which is hopefully close to the input mean
76.7795234718 which variance = stdev squared
5.29517640642


Find more distributions and random functions here: http://docs.scipy.org/doc/numpy/reference/routines.random.html

### Exercise 1

1) Create a 4x5 array of integers between 0 and 19

In [90]:
np.random.randint(20, size=(4, 5))
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

2) Create a 50x500 array with a mean of 20 and variance of 100. Save it to a variable called  biggie

In [79]:
biggie=np.random.normal(20,10,(50,500))
print biggie.mean()
print biggie.var()

19.9346085595
99.2782708086


3) Change the mean of the array to a value within 1 of 0 and the variance within 1 of 25. Think about what the mean and the variance represent and try using various mathematical operations.

In [91]:
biggie2=biggie-20 #to change mean you subtract
print biggie2.mean()
biggie3= biggie*1/2 #to change variance you multiply or divide
print biggie3.var()

-0.0653914404562
24.8195677022


## Pandas (python package)

Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive.

Pandas is great for tabular/indexed data

In [48]:
# NOTE: you should normally put all your imports at the top of the file
import pandas as pd

In [49]:
data = pd.read_csv('../data/nytimes.csv')

In [50]:
# Note here we're calling the head method on the dataframe to return the 'head' of the 
# dataframe, in this case the first 4 lines
# head() actually creates a new copy of the data, this is important later in the course!
data.head(4)

Age  Gender  Impressions  Clicks  Signed_In
0   36       0            3       0          1
1   73       1            3       0          1
2   30       0            3       0          1
3   49       1            3       0          1

In [51]:
data[0:4]

Age  Gender  Impressions  Clicks  Signed_In
0   36       0            3       0          1
1   73       1            3       0          1
2   30       0            3       0          1
3   49       1            3       0          1

In [52]:
# Each DataFrame has an index
# Sometimes you will need to reindex
data.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            458431, 458432, 458433, 458434, 458435, 458436, 458437, 458438,
            458439, 458440],
           dtype='int64', length=458441)

In [8]:
# This is a Series (column)
# A DataFrame is made of of several Series with the same index
data.Age

0         36
1         73
2         30
3         49
4         47
5         47
6          0
7         46
8         16
9         52
10         0
11        21
12         0
13        57
14        31
15         0
16        40
17        31
18        38
19         0
20        59
21        61
22        48
23        29
24         0
25        19
26        19
27        48
28        48
29        21
          ..
458411    55
458412    68
458413     0
458414    21
458415    35
458416    26
458417    41
458418    58
458419    46
458420    45
458421    46
458422    47
458423    22
458424    21
458425    40
458426    49
458427    43
458428    40
458429    49
458430     0
458431    21
458432    30
458433    21
458434    61
458435    51
458436     0
458437     0
458438    72
458439     0
458440     0
Name: Age, dtype: int64

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458441 entries, 0 to 458440
Data columns (total 5 columns):
Age            458441 non-null int64
Gender         458441 non-null int64
Impressions    458441 non-null int64
Clicks         458441 non-null int64
Signed_In      458441 non-null int64
dtypes: int64(5)
memory usage: 21.0 MB


In [54]:
data.describe().T

count       mean        std  min  25%  50%  75%  max
Age          458441  29.482551  23.607034    0    0   31   48  108
Gender       458441   0.367037   0.481997    0    0    0    1    1
Impressions  458441   5.007316   2.239349    0    3    5    6   20
Clicks       458441   0.092594   0.309973    0    0    0    0    4
Signed_In    458441   0.700930   0.457851    0    0    1    1    1

In [55]:
# We can change this data into numpy
type(data.Age.values)

numpy.ndarray

#### Just like in numpy, we can use mean, var, and other functions on the data

In [56]:
print data.Age.mean()
print data.Age.var()
print data.Age.max()
print data.Age.min()

29.4825506445
557.292044027
108
0


In [57]:
# Function that groups users by age.
def map_age_category(x):
    if x < 18:
        return '1'
    elif x < 25:
        return '2'
    elif x < 32:
        return '3'
    elif x < 45:
        return '4'
    else:
        return '5'

data['age_categories'] = data['Age'].apply(map_age_category) #data[""] square brackets add a new column

In [58]:
data.head(4)

Age  Gender  Impressions  Clicks  Signed_In age_categories
0   36       0            3       0          1              4
1   73       1            3       0          1              5
2   30       0            3       0          1              3
3   49       1            3       0          1              5

#### Sorting data

In [59]:
data.sort_index(axis=1, ascending=False).head()

age_categories  Signed_In  Impressions  Gender  Clicks  Age
0              4          1            3       0       0   36
1              5          1            3       1       0   73
2              3          1            3       0       0   30
3              5          1            3       1       0   49
4              5          1           11       1       0   47

In [60]:
data.sort('Age').head()

/Users/chc/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Age  Gender  Impressions  Clicks  Signed_In age_categories
458440    0       0            3       0          0              1
125795    0       0            3       0          0              1
312007    0       0            6       0          0              1
312003    0       0            6       0          0              1
311999    0       0            9       0          0              1

In [61]:
ran_data = [
    ['a', 1]
    , ['b', 2]
    , ['c', 3]
]
df = pd.DataFrame(ran_data, columns=['col_a', 'numeric'])
df

col_a  numeric
0     a        1
1     b        2
2     c        3

#### Indexing functions

Pandas Dataframes support various methods for indexing:

- .iloc
- .loc
- .ix

In [62]:
df

col_a  numeric
0     a        1
1     b        2
2     c        3

In [63]:
# iloc accesses a row by its row number
df.iloc[0]

col_a      a
numeric    1
Name: 0, dtype: object

In [64]:
df.set_index('col_a', inplace = True)
df

numeric
col_a         
a            1
b            2
c            3

In [1]:
# loc accesses a dataframe row by its index label (or column label)
df.loc['a'] = 5
df.loc['b'] = 3

NameError: name 'df' is not defined

In [66]:
df

numeric
col_a         
a            5
b            3
c            3

In [80]:
# This can be used to add new columns
df['C']='fat'
df

numeric  D    C
col_a                 
a            5  5  fat
b            3  3  fat
c            3  3  fat

In [72]:
# is equivalent to:
df['D'] = df.loc[:,'numeric']

df

numeric  D
col_a            
a            5  5
b            3  3
c            3  3

In [92]:
df.ix[0] = 'fat' #changes index 2 to 2
df

numeric    D    C
col_a                  
a         fat  fat  fat
b           2    2    2
c           2    2    2

.ix is the generic form of indexers

Values can be set by index and index + column

In [93]:

df.ix[2, 'C'] = 'baby'

df

numeric    D     C
col_a                   
a         fat  fat   fat
b           2    2     2
c           2    2  baby

### Combining DataFrames
#### Appending
We can append dataframes together

In [94]:
df_combine = df.append(df)
df_combine

numeric    D     C
col_a                   
a         fat  fat   fat
b           2    2     2
c           2    2  baby
a         fat  fat   fat
b           2    2     2
c           2    2  baby

In [95]:
# When DataFrames are appended together, we often need to create a new index
df_combine.reset_index()

col_a numeric    D     C
0     a     fat  fat   fat
1     b       2    2     2
2     c       2    2  baby
3     a     fat  fat   fat
4     b       2    2     2
5     c       2    2  baby

#### Join lets us join together dataframes using their index

In [96]:
df_2 = pd.DataFrame([1, 2, 3], columns=['col'])
df_2

col
0    1
1    2
2    3

In [97]:
# The default is left join, so Null values are placed
# where values are misssing
df.join(df_2)


numeric    D     C  col
col_a                        
a         fat  fat   fat  NaN
b           2    2     2  NaN
c           2    2  baby  NaN

In [98]:
# reset the index
df_1 = df.reset_index()
df_1

col_a numeric    D     C
0     a     fat  fat   fat
1     b       2    2     2
2     c       2    2  baby

In [99]:
# try joining again:
df_1.join(df_2)


col_a numeric    D     C  col
0     a     fat  fat   fat    1
1     b       2    2     2    2
2     c       2    2  baby    3

#### Merge allows us to join on any fields

In [100]:
# Merge has a default of inner join
# So where the join misses rows are omitted
df.merge(df_2, left_on='numeric', right_on='col')

numeric  D     C  col
0       2  2     2    2
1       2  2  baby    2

### Concat combines a list of DataFrames together

In [140]:
# It can be used like append
pd.concat([df, df])

numeric  C  D
col_a               
a            5  5  5
b            3  3  3
c            2  3  2
a            5  5  5
b            3  3  3
c            2  3  2

In [101]:
# But concat will create a spare DataFrame when columns don't match
# This can create huge dataframes when mismatches occur
pd.concat([df, df_2])

C    D  col numeric
col_a                        
a       fat  fat  NaN     fat
b         2    2  NaN       2
c      baby    2  NaN       2
0       NaN  NaN    1     NaN
1       NaN  NaN    2     NaN
2       NaN  NaN    3     NaN

## Exercise 2
### Combining numpy and pandas

1) Create 2 arrays of integers

One should be created using np.random

In [104]:
ran_data1 = np.random.randint(10,size=(5,2))
ran_data2 = np.random.randint(20, size=(8,2))
print ran_data1
print ran_data2

[[4 3]
 [6 5]
 [3 9]
 [6 0]
 [1 0]]
[[ 0  3]
 [10  4]
 [12  0]
 [14 17]
 [ 5 19]
 [16  5]
 [ 6  1]
 [ 5 17]]


2) Turn those arrays into pandas DataFrames

The columns can be named numerically

In [109]:
df_1 = pd.DataFrame(ran_data1, columns=['fat', 'baby'])
df_2 = pd.DataFrame(ran_data2, columns=['1','2'])
print df_1
print df_2

   fat  baby
0    4     3
1    6     5
2    3     9
3    6     0
4    1     0
    1   2
0   0   3
1  10   4
2  12   0
3  14  17
4   5  19
5  16   5
6   6   1
7   5  17


3) Use some of the summary functions on the dataframes and arrays

Show how mean and var give the same response in python and numpy

In [112]:
print df_1.describe()

           fat      baby
count  5.00000  5.000000
mean   4.00000  3.400000
std    2.12132  3.781534
min    1.00000  0.000000
25%    3.00000  0.000000
50%    4.00000  3.000000
75%    6.00000  5.000000
max    6.00000  9.000000



4) Add an extra index using .loc

In [115]:
df_1.loc[:,'boy']= 'Bubble'
df_2.loc[:,'girl'] = 'Valerie'
df_1

fat  baby     boy
0    4     3  Bubble
1    6     5  Bubble
2    3     9  Bubble
3    6     0  Bubble
4    1     0  Bubble

5) Using merge or join, create a single DataFrame from the two

In [117]:
df_1.join(df_2)

fat  baby     boy   1   2     girl
0    4     3  Bubble   0   3  Valerie
1    6     5  Bubble  10   4  Valerie
2    3     9  Bubble  12   0  Valerie
3    6     0  Bubble  14  17  Valerie
4    1     0  Bubble   5  19  Valerie

6) Try testing out the groupby functions

df.groupby(column).agg (agg can be an aggregate function, try sum, max, min...)

Resources can be found here: http://pandas.pydata.org/pandas-docs/stable/10min.html#grouping


## Plotting!

In [ ]:
import pandas.io.data
import datetime
import matplotlib.pyplot as plt

%matplotlib inline

mu, sigma = 0, 0.1
normal_dist = np.random.normal(mu, sigma, 1000)
aapl = pd.io.data.get_data_yahoo('FB', 
                                 start=datetime.datetime(2015, 4, 1), 
                                 end=datetime.datetime(2015, 4, 28))
aapl.head()

## MatPlotLib

MatPlotLib is a standard, granular method for building visualizations. Although tried and true, it can be cumbersome compared to other higher level packages such as Seaborn or Bokeh. Note most visualization packages use matplotlib as their base.

In [ ]:
fig = plt.figure(figsize=(20,16))

ax = fig.add_subplot(2,2,1)
ax.plot(aapl.index, aapl['Close'])
ax.set_title('Line plots', size=24)

ax = fig.add_subplot(2,2,2)
ax.plot(aapl['Close'], 'o')
ax.set_title('Scatter plots', size=24)

ax = fig.add_subplot(2,2,3)
ax.hist(normal_dist, bins=50)
ax.set_title('Histograms', size=24)
ax.set_xlabel('count', size=16)

ax = fig.add_subplot(2,2,4)
ax.boxplot(normal_dist)
ax.set_title('Boxplots', size=24)

### Bokeh
To install Bokeh, go to a terminal and type:

`conda install bokeh` 

Bokeh is built by the same people that created Anaconda (Continuum Analytics) and is designed out of the box for web display, making it nice for creating presentation ready, interactive visuals quickly. Labs in this course will be shown in Bokeh. Checkout http://bokeh.pydata.org/en/latest/docs/quickstart.html#concepts to see some of the range of capabilities.

In [ ]:
from bokeh.plotting import figure, output_notebook,show
output_notebook()

In [ ]:
# prepare some data
x = aapl.Low
y = aapl['High']

# create a new plot with a title and axis labels
p = figure(title="Stock High vs. Low", x_axis_label='Low', y_axis_label='High')

# add a line renderer with legend and line thickness
p.circle(x, y, legend="High vs. Low", line_width=2)

# show the results
show(p)

In [ ]:
x = aapl.index
y = aapl.Close
p = figure(title="Stock Open & Close over time", x_axis_label='Date', y_axis_label='High',x_axis_type="datetime")
# Note that I've declared the x_axis_type
p.square(x, y, legend="Close")
p.circle(x,aapl.Open,legend='Open',color='red')
# show the results
show(p)

## Pandas Plotting!

The plot method is a great, quick way to visualize your dataframes. By selecting the columns you care to view, calling .plot() on the dataframe defaults to a line chart vs. the index.

We will be revisiting this so just take a second to appreciate what can be done with one line of code.

In [ ]:
aapl[['Open','Close']].plot()

In [ ]:
aapl[['High','Low','Open','Close']].plot(kind='box')